spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  #        transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PW}

  datasource:
    url: ${DB_URL} # mysql:3306/?? ??
    username: root
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration: 300000 # 5m
  refresh-token-expiration: 86400000 # 24h

admin:
  username: ${ADMIN_NAME}
  password: ${ADMIN_PW}

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs
  default-consumes-media-type: application/json
  auto-tag-classes: true
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
